<Section>
    size: root.width, root.height
    pos: root.x, root.top - self.height
    canvas.before:
        Color:
            rgba: 0.1,0.1,0.1,1
        Line:  
            rectangle: self.x, self.y, self.width, self.height
    Button:
        id: title
        pos: root.x, root.top - self.height
        size: root.width, 40
        text: "Default Title"
        disabled: True
    ScrollView:
        pos: root.x, root.top - root.height-title.height
        size: root.width, root.height
        BoxLayout:
            padding: 15,15,15,15
            spacing: 5
            size_hint_y: None
            pos: root.x, root.top - self.height - title.height
            size: root.width, self.minimum_height
            orientation: 'vertical'
            id: body

<SourceNode>:
    pos: root.x, root.top - self.height
    size: root.width, root.height
    BoxLayout:
        canvas.before:
            Color:
                rgba: 1, 0, 0, 1
            Line:
                width: 1
                rectangle: self.x, self.y, self.width, self.height
        pos: root.x, root.top - self.height
        size: root.width, root.height
        Label:
            text: 'widget'

<TargetNode>:
    pos: root.x, root.top - self.height
    size: root.width, root.height
    BoxLayout:
        canvas.before:
            Color:
                rgba: 1,1, 0, 1
            Line:
                width: 1
                rectangle: self.x, self.y, self.width, self.height
        pos: root.x, root.top - self.height
        size: root.width, root.height

<CallGraphNode>:
    size_hint_y: None
    size: root.width, self.height
    pos: root.x, root.top - self.height
    BoxLayout:
        id: content
        canvas.before:
            Color:
                rgba: 0.6,0.6,0.6,1
            Line:
                points: self.x-(25/2),self.top-25,self.x,self.top-25
            Color:
                rgba: 0.4,0.4,0.4,1
            Rectangle: 
                size: self.width, self.height
                pos: self.x, self.y
        pos: root.x, root.top-50
        size: root.width, 50
        orientation: "horizontal"
        Button:
            size_hint: None, None
            size: 50,50
            pos: root.x, root.top-50
            text: ">"
            on_press: root.OnButtonDropDownPress()
        Label:
            id: label
            text: "Module"
        Button:
            id: options
            size_hint: None, None
            size:50,50
            pos: root.x, root.top-50
            text: "..."
            on_press: root.OnButtonOptionsPress()
    BoxLayout:
        id: childBody 
        spacing: 15  
        canvas.before:
            Color:
                rgba: 0.6,0.6,0.6,1
            Line:
                points: self.x-(25/2), self.top+15, self.x-(25/2),   (root.GetLastChildY()-25 if (root.child_count > 0) else self.top+15)
        size_hint_y: None
        orientation: "vertical"
        pos: root.x + 25, root.top - self.minimum_height - 50 - 15
        size: root.width - 25, self.minimum_height

<ModuleResource>
    size_hint_y: None
    size: root.width, 30
    pos: root.x, root.top - self.height
    Button:
        id: modulebutton
        text: "Module"
        pos: root.x, root.top - self.height
        size: root.width, 30
        on_press: root.OnPress()




<PopupContentRegion>
    ScrollView:
        pos: root.x, root.top - root.height
        size: root.width, root.height
        id: scroll
        BoxLayout:
            padding: 15,15,15,15
            spacing: 40
            size_hint_y: None
            pos: root.x, root.top - self.height
            size: root.width, self.minimum_height
            orientation: 'vertical'
            id: body

<ParamModule>
    size_hint_y: None
    Label:
        id: label
        text: "Fixed Parameter"
        size: self.size
        size: root.width, 50
        pos: root.x, root.top- root.height + 50
        text_size: self.size
    BoxLayout:
        padding: 5
        canvas.before:
            Color:
                rgba: 0.4,0.4,0.4,1
            Rectangle: 
                size: self.width, self.height
                pos: self.x, self.y
        orientation: "horizontal"
        size:root.width, 50
        pos: root.x, root.top- root.height
        id: body
        Button: 
            id: set
            size_hint_x: None
            size: 50, 50
            pos: root.x, root.top- root.height
            text: "Set"
            on_press: root.OnPressSet()

<RunModuleButton>
    size_hint_y: None
    Label:
        id: label
        text: "Func1"
        size: self.size
        size: root.width, 50
        pos: root.x, root.top- root.height + 50
        text_size: self.size
    BoxLayout:
        padding: 5
        canvas.before:
            Color:
                rgba: 0.4,0.4,0.4,1
            Rectangle: 
                size: self.width, self.height
                pos: self.x, self.y
        orientation: "horizontal"
        size:root.width, 50
        pos: root.x, root.top- root.height
        id: body
        Button: 
            id: run
            size_hint_x: None
            size: 50, 50
            pos: root.x, root.top- root.height
            text: "Run"
            on_press: root.OnPressRun()

<ParamField>
    BoxLayout:
        size_hint_y: None
        orientation: "horizontal"
        size: root.width, root.height
        pos: root.x, root.top- self.height
        id: body
        Label:
            size_hint_y: None
            id: label
            text: "Input"
            size: root.width, root.height
            pos: root.x, root.top - self.height
        TextInput:
            id: param
            size_hint_y: None
            size: root.width, root.height
            pos: root.x, root.top - self.height
            text: "0"
            halign: "center"
            padding_y: [self.height / 2.0 - (self.line_height / 2.0) * len(self._lines), 0]
            multiline: False


<RemoveCallNodeButton>
    Button:
        id: RemoveWidget
        text: "Remove Module"
        pos: root.x, root.top - self.height
        size: root.width, 30
        on_press: root.RemoveWidget()

<ToolClearAll>
    size_hint_y: None
    size: self.size 
    Button:
        disabled: False
        halign: "center"
        size_hint_x: None
        size_hint_y: None
        size: 50, 50
        pos: root.x+root.width/2 -self.width/2, root.top - self.height
        text: "Clear All"
        on_press: root.ClearAll()
        font_size: 12

<ToolOpenModule>
    size_hint_y: None
    size: self.size 
    Button:
        halign: "center"
        size_hint_x: None
        size_hint_y: None
        size: 50, 50
        pos: root.x+root.width/2 -self.width/2, root.top - self.height
        text: "Open"
        on_press: root.OpenModule()
        font_size: 12


    
<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            path: ""
        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)